import discord
from discord import app_commands
import sqlite3
import json
import os
import sys
from dotenv import load_dotenv  # NEW: Import dotenv

# Import our existing database connection
from render.database import get_db_connection, setup_database

class ArmoryBot(discord.Client):
    def __init__(self):
        super().__init__(intents=discord.Intents.default())
        self.tree = app_commands.CommandTree(self)

    async def setup_hook(self):
        # This syncs the slash commands to Discord when the bot boots up
        await self.tree.sync()
        print("✅ Slash commands synced!")

client = ArmoryBot()

@client.event
async def on_ready():
    print(f'🤖 Logged in as {client.user} (ID: {client.user.id})') # type: ignore
    print('Ready to receive profession data!')
    setup_database() # Ensure tables exist

@client.tree.command(name="sync_professions", description="Upload your profession .json file from the AMW Addon.")
async def sync_professions(interaction: discord.Interaction, file: discord.Attachment):
    """Slash command that accepts a .json file upload."""
    
    if not file.filename.endswith('.json'):
        await interaction.response.send_message("❌ Please upload a valid `.json` file generated by the addon.", ephemeral=True)
        return

    # Defer the response since reading files/databases can take a second
    await interaction.response.defer(ephemeral=False)

    try:
        # Download and parse the JSON file from Discord
        file_bytes = await file.read()
        data = json.loads(file_bytes.decode('utf-8'))

        # If the addon exports a single object, wrap it in a list so we can always loop safely
        if isinstance(data, dict):
            data = [data]

        conn = get_db_connection()
        c = conn.cursor()

        total_recipes = 0
        professions_updated = []
        char_name_display = "Unknown"

        for prof_data in data:
            # Safely grab the keys, falling back to older names just in case
            char_name = prof_data.get("player") or prof_data.get("character")
            prof_name = prof_data.get("profession")
            skill = prof_data.get("level") or prof_data.get("skillLevel", 0)
            max_skill = prof_data.get("maxLevel", 0) # Defaults to 0 if your addon doesn't export it
            recipes = prof_data.get("recipes", [])

            if not char_name or not prof_name:
                continue

            char_name_display = char_name

            # Insert or update the main profession stats
            c.execute("""
                INSERT OR REPLACE INTO professions (character_name, profession, skill_level, max_level)
                VALUES (?, ?, ?, ?)
            """, (char_name, prof_name, skill, max_skill))

            # Insert all known recipes
            for recipe in recipes:
                c.execute("""
                    INSERT OR REPLACE INTO known_recipes (character_name, profession, recipe_id, recipe_name)
                    VALUES (?, ?, ?, ?)
                """, (char_name, prof_name, recipe.get("id"), recipe.get("name")))
                total_recipes += 1
                
            professions_updated.append(f"**{prof_name}** ({skill})")

        conn.commit()
        conn.close()

        db_path = os.path.join("asset", "guild.db")
        sql_path = os.path.join("asset", "guild.sql")
        
        import sqlite3 # Make sure this is imported if it isn't at the top!
        dump_conn = sqlite3.connect(db_path)
        with open(sql_path, 'w', encoding='utf-8') as f:
            for line in dump_conn.iterdump():
                f.write('%s\n' % line)
        dump_conn.close()

        if professions_updated:
            joined_profs = ", ".join(professions_updated)
            await interaction.followup.send(f"✅ Successfully updated {joined_profs} for **{char_name_display}**! Added {total_recipes} total recipes to the database.")
        else:
            await interaction.followup.send("❌ No valid profession data found in the JSON file.")

    except Exception as e:
        await interaction.followup.send(f"❌ An error occurred while processing the file: {e}")

# --- START THE BOT ---
if __name__ == "__main__":
    if sys.platform == 'win32':
        import asyncio
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
        
    # Load environment variables from your .env file
    load_dotenv()
    
    # Grab the token safely
    TOKEN = os.getenv("DISCORD_TOKEN")
    
    if not TOKEN:
        print("❌ ERROR: DISCORD_TOKEN not found! Check your .env file.")
        sys.exit(1)
        
    client.run(TOKEN)